"""initial db commit

Revision ID: f90ec2786eac
Revises: 
Create Date: 2024-08-11 09:38:03.300251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f90ec2786eac'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activity_name', sa.String(), nullable=False),
    sa.Column('activity_description', sa.String(), nullable=False),
    sa.Column('activity_image', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('destinations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('country', sa.String(length=50), nullable=False),
    sa.Column('image', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('_password_hash', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('activity_destinations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('destination_id', sa.Integer(), nullable=True),
    sa.Column('activity_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], name=op.f('fk_activity_destinations_activity_id_activities')),
    sa.ForeignKeyConstraint(['destination_id'], ['destinations.id'], name=op.f('fk_activity_destinations_destination_id_destinations')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_activity_destinations_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('activity_destinations')
    op.drop_table('users')
    op.drop_table('destinations')
    op.drop_table('activities')
    # ### end Alembic commands ###
